(load "std/std.scm")
; (define username (read))
; (define (repeat i stmt) (if (/= i 0) (do (stmt) (repeat (- i 1) stmt)) '()))
; (define (print-three-times str) (repeat 3 (lambda () (write (concat "hello user " str)))))
; (print-three-times username)
(write (string.from (+ -4 -0o13 -0b11 0xFF) (+ 0.5 -0.25) "kek \t \2022 \n" \tab \k \2022 \newline))
